
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: arist_app_development
test:
  <<: *default
  database: arist_app_test
production:
  <<: *default
  password: <%= ENV['ARIST_APP_DATABASE_PASSWORD'] %>
